### ISSUE TITLE
[Bug] Drawing a portal's hitbox crashes the game

### ISSUE THREAD

**Issue by Frostplays-ZERO** [Mari0-CE/Mari0-Community-Edition#102]
Specific error: `"portalwall.lua:20: attempt to call field 'point' (a nil value)"`
Investigation of the lua file reveals that it's trying to call `love.graphics.point`, which is presumably invalid

Changing portalwall.lua to [this](https://github.com/HugoBDesigner/Mari0-Community-Edition/files/2360388/portalwall.txt) (renamed to txt so it could upload to github, rename back to lua before inserting) solved the problem.

**Comment by Noahkiq** [comment]
frostplays provided a patch that works fine... why hasn't this been added yet? :thinking:
