### ISSUE TITLE
Pause game for n seconds

### ISSUE THREAD

**Issue by Someone671** [Mari0-CE/Mari0-Community-Edition#114]
This is another animation option. Though it might look similiar to sleep/wait, it's **not**. This new option **pauses** the game (like enemies' movement, mario, his motions and other stuff like the time though maybe not circuits) and the animation can do something when the game is paused. This is useful for dynamic boss fights (for example, having a pillar fall down when mario approach the boss, pausing the game activites is used to make it dramatic. So mario would be stuck until the pillar fully falls down (when the _n_ amount of time runs out, preferably after the pillar fully falls down) and he continues moving in the direction before the pause.)

**Comment by HugoBDesigner** [comment]
Moved to #59
