### ISSUE TITLE
[Suggestion] Variables for Animations

### ISSUE THREAD

**Issue by masterminer176** [Mari0-CE/Mari0-Community-Edition#125]
Basically would add some variable based blocks into the animation system. A variable, ideally, would be a value (numeric, text, or true/false) that can be read & manipulated. Here's an example:

There's a guy to check if you have a pass to enter a building, there is a variable of wether or not you have a pass, buying a pass will set the value of the variable to true, the guy will check the variable to see if you have it, then let you in.

This would open up a plethera of options for mapmakers involving multiple game states. Some more ideal features to this system could be: 
1.Variables linking with a suspend point, to not lose progress.
2.Variable reading as a condition for animations, and setting as a block.
3.More if I can come up with some.

This is probably a massive undertaking, so I don't expect this to come out soon, but if it comes out at all, I'd be a happy camper indeed.

**Comment by Frostplays-ZERO** [comment]
Hello. 
Download the latest commit. 
Read the 0readme.md. 
Play with it.
Tell the stabyourself forums about the latest advancements in Mari0 Technology.

**Comment by Frostplays-ZERO** [comment]
By the way, I was going to make a small example mappack. My mapmaking skills in this regard seem to be on par with Maurice's. I'll release something of the mappack soon.
