### ISSUE TITLE
[Bug] Game crashes when placing/drawing specific animated tiles

### ISSUE THREAD

**Issue by villager103** [Mari0-CE/Mari0-Community-Edition#127]
![image](https://user-images.githubusercontent.com/36653409/47961436-fb253c00-e05a-11e8-9d35-7f421d274314.png)
It only seems to happen with specific animated tiles. Upon examination of the .txt files, there is nothing wrong with them, nor is there anything wrong with the images themselves, I double-checked to see if the dimensions are correct, and they are.

You can see and select this tile from the menu without the game crashing, but when you place it in the level, or one gets drawn in a level that had them previously, the game crashes.

The only modifications to the game are the font, fontback, smallfont, 1uptext and replaced sound effects, which shouldn't be interfering with the animated tiles anyway.

**Comment by Frostplays-ZERO** [comment]
You know there's a "sounds" folder in your mappack folder, right? Well, it's not automatically created, but you don't need to replace sounds in the .love anymore.

**Comment by Frostplays-ZERO** [comment]
Edit: this seems to be a problem with the whole "modcustomtiles" thing, which I never should have left in here. 

http://forum.stabyourself.net/viewtopic.php?f=13&t=4649

Can someone please help me make this not broken?

**Comment by HugoBDesigner** [comment]
I sent you an invite, but you should still be able to sent pull requests without being a member

**Comment by Frostplays-ZERO** [comment]
Thank you. I promise I won't abuse my newfound ability to commit directly.
