### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by MistahJorge** [Mari0-CE/Mari0-Community-Edition#134]
![crash](https://user-images.githubusercontent.com/33864034/50439738-ffe3cf00-08ea-11e9-97e5-050c8b51fd44.png)

**Comment by HugoBDesigner** [comment]
Hi, could you give us a bit more information about what you did to get that crash? Attempting to reproduce it on my end wielded no error.

**Comment by MistahJorge** [comment]
Just tried to recreate the bug, after some tests i found out that what you need to do is to shoot up a portal near the flag pole, you need to do it when you're high enough to be off stage, i managed to do it in Level 1-1, 1-2, 1-3 and 1-1 from 0'Brothers to try a different mappack

**Comment by Frostplays-ZERO** [comment]
I think it's trying to check the properties of a nonexistent tile.

Quick patch:

change line 4193 of game.lua to 
`if cox and tilequads[map[cox][coy]] and tilequads[map[cox][coy][1]]:getproperty("mirror", cox, coy) then`
and see if that works.

**Comment by MistahJorge** [comment]
Okay, i just tested it and it appears to be fixed so far
