### ISSUE TITLE
[Bug] Entering "- -" as a level crashes

### ISSUE THREAD

**Issue by Someone671** [Mari0-CE/Mari0-Community-Edition#159]
Self-explanatory
![error](https://user-images.githubusercontent.com/42733310/77332062-209c0e00-6d54-11ea-94af-895dd44fe9b7.png)
(unrelated sidenote: World --- in the original SMB is world 40-40)

**Comment by HugoBDesigner** [comment]
Didn't happen to me. Adding anything other than numbers just added a level after the last one.
