### ISSUE TITLE
goomba wall ?

### ISSUE THREAD

**Issue by Mehmet-dev** [Mari0-CE/Mari0-Community-Edition#162]
![2020-07-20-170847_1280x960_scrot](https://user-images.githubusercontent.com/64650857/87962922-a2ad0100-cac0-11ea-8408-b3de5c0e4875.png)

**Comment by HugoBDesigner** [comment]
This type of enemy can be achieved via Custom Enemies already.

**Comment by Mehmet-dev** [comment]
but it is on classic game map ?
