### ISSUE TITLE
player can clip into the walls via portals.

### ISSUE THREAD

**Issue by Erdal-oz** [Mari0-CE/Mari0-Community-Edition#165]
![2020-07-20-193328_1280x960_scrot](https://user-images.githubusercontent.com/64650857/87964297-ac376880-cac2-11ea-96ab-265d14d6aa74.png)

**Comment by HugoBDesigner** [comment]
@Mehmet-dev Would you mind sharing the method through which you managed to have that bug happen? I can't seem to reproduce it on my end.

**Comment by Mehmet-dev** [comment]
I am constantly teleporting while running between these two portals
