### ISSUE TITLE
player dies when jumps to the wing

### ISSUE THREAD

**Issue by Erdal-oz** [Mari0-CE/Mari0-Community-Edition#166]
![2020-07-20-190013_1280x960_scrot](https://user-images.githubusercontent.com/64650857/87965298-2fa58980-cac4-11ea-97f3-73aadcead73b.png)

**Comment by HugoBDesigner** [comment]
@Mehmet-dev I was unable to reproduce this bug. Would you mind sharing a video or explanation on how this bug occurs?

**Comment by Mehmet-dev** [comment]
I am just jumping into the wing of the koopa
