### ISSUE TITLE
Error on level loading

### ISSUE THREAD

**Issue by MinDC249** [Mari0-CE/Mari0-Community-Edition#178]
when I play "in the cloud" mappack for SE, CE is broken

![image](https://user-images.githubusercontent.com/85324387/120733733-ec081280-c511-11eb-8a00-ed336e153a80.png)

**Comment by HugoBDesigner** [comment]
Hello, thanks for the report! I tested the mappack but couldn't reproduce the error. I also tried the outdated "beta 8" version of the mappack, but that version didn't cause the error either. Can you confirm that you're playing the latest version of Community Edition?

I've just posted a new release, which is actually just the up-to-date code compiled into a .love file for convenience:
https://github.com/Mari0-CE/Mari0-Community-Edition/releases/tag/1.5

If the error persists, please comment here again with more details on how to reproduce the error. Thanks!

**Comment by dc249** [comment]
OK!

Vào Th 7, 5 thg 6, 2021 vào lúc 01:59 Hugo ***@***.***> đã
viết:

**Comment by dc249** [comment]
I play vision 1.4

Vào CN, 6 thg 6, 2021 vào lúc 17:21 Nguyen Minh Dang ***@***.***>
đã viết:

**Comment by HugoBDesigner** [comment]
Assuming this is an old issue, so I'm closing. If the error persists, please open this issue again and provide further details.
