### ISSUE TITLE
1-Up fix for shell enemies

### ISSUE THREAD

**Issue by HugoBDesigner** [Mari0-CE/Mari0-Community-Edition#179]
Bouncing on shell enemies continuously makes it so that, once you hit the 1-Up combo threshold, it oscillates between the 1-Up and 8000 points.

**Comment by HugoBDesigner** [comment]
I double-checked original SMB footage, and shell enemies don't seem to give points during 1-Ups. Also, stars _should_ give points, so I updated the issue to reflect that.

**Comment by MinDC249** [comment]
In SMB, if you kick a shell, the game will give you points when the shell kill enemies, the point number is :100, 200, 400, 800, 1000,... After 8000 point, it will give you 1-up

**Comment by MinDC249** [comment]
Oh, I forgot, the star give you points(yes, you right) but it don't give you bonus points and 1-up
