### ISSUE TITLE
"Mirror" Tile property doesn't work

### ISSUE THREAD

**Issue by HugoBDesigner** [Mari0-CE/Mari0-Community-Edition#180]
The "Mirror" tile property shows the reflected path correctly, but when shooting a portal at it, the portal doesn't reflect.

**Comment by MinDC249** [comment]
When have the next vision

**Comment by HugoBDesigner** [comment]
I'm working on some bugfixes (in fact, I already fixed this bug). But we'll see. I'm only focusing on bugfixes and slight quality-of-life tweaks, nothing big

**Comment by MinDC249** [comment]
I have checked the 1.6 vision, but the mirror bugs is continue :(

**Comment by HugoBDesigner** [comment]
I had uploaded the wrong .love file by mistake. I've updated the release with the correct version now
