### ISSUE TITLE
Power Jump glitch

### ISSUE THREAD

**Issue by MistahJorge** [Mari0-CE/Mari0-Community-Edition#181]
A glitch that can be abused to potentially double the height of your jump (I didn't have a better name for this).
To reproduce you need to:
1.  Catch either a mushroom or a flower power up while mid air;
2. Jump again precisely when the screen pauses and mario grows/transforms;
3. You can hold the jump button for higher jumps, just like you do when you jump normally.

Other notes:

- This does not work with a game pad (at least to me), so keyboard only glitch.
- Catching power ups as fire mario doesn't cause a screen pause, which makes it impossible to power jump as fire mario.
- If you didn't jump but managed to catch a power up while mid air (example: falling from a ledge) you have to double tap jump for it to work, I wish don't knew why...

Edit: by the way i posted a map pack on the forum that contains some examples of levels that need this glitch to be completed.

**Comment by HugoBDesigner** [comment]
I'm just gonna quote @Qwerbey's comment on the forums, since they know about this more than I do:
> That's actually a feature, in order to replicate a bug in Super Mario Brothers. I remember Maurice posting something about it, but I can't seem to find it.

So I'm closing this as it seems intended, but if anyone else believes this should be removed or changed in any way, feel free to comment in this issue.
