### ISSUE TITLE
Poison Mushroom Sprites

### ISSUE THREAD

**Issue by MinDC249** [Mari0-CE/Mari0-Community-Edition#184]
Have a little pixel look doesn't right in Poison Mushroom Sprites (that it)

**Comment by HugoBDesigner** [comment]
I don't understand what you're trying to say. Could you maybe try to reword it?

**Comment by MinDC249** [comment]
Sorry, I don’t speak English as well:
You need check again the poison mushroom’s sprites

**Comment by HugoBDesigner** [comment]
It looks right to me.
![image](https://user-images.githubusercontent.com/6296061/134730187-e03e04f1-9154-48c9-a976-ee578c83cf11.png)

**Comment by MinDC249** [comment]
There! Has a white pixel at the bott
![134730187-e03e04f1-9154-48c9-a976-ee578c83cf11](https://user-images.githubusercontent.com/85324387/134751701-ffef9d10-9baf-43d6-84fe-e9bda7c29712.png)
om
