### ISSUE TITLE
Building for web?

### ISSUE THREAD

**Issue by Erisfiregamer1** [Mari0-CE/Mari0-Community-Edition#190]
Would it be possible to build this for the web? I want to put this on the web for people to play, but I can't find a web builder that can build it for the web.

**Comment by HugoBDesigner** [comment]
I don't think it's viable to build for web, as that would require a massive code overhaul to make it work well online. Not to mention, so much of the mod relies on local storage, that it'd likely require a dedicated server to host the game. Anyone's free to try and port the game, but I wouldn't hold my breath.
