### ISSUE TITLE
Crashes same place every game

### ISSUE THREAD

**Issue by nunyafukkinbizness** [Mari0-CE/Mari0-Community-Edition#192]
Crashes same place every game
![Screenshot from 2022-05-01 06-20-50](https://user-images.githubusercontent.com/76876883/166148093-d3da68d8-47e9-44e2-8d6f-d13faecddd41.png)

**Comment by HugoBDesigner** [comment]
Duplicate of #191

**Comment by nunyafukkinbizness** [comment]
If this issue is closed where is the solution? Did I waste my time contacting you?

    On Wednesday, May 4, 2022, 07:43:50 PM PDT, Hugo ***@***.***> wrote:  
 
 


Duplicate of #191

**Comment by nunyafukkinbizness** [comment]
If there is no fix for this bug I should uninstall becaause if it doesn't work it's a waste of space!

    On Wednesday, May 4, 2022, 07:43:50 PM PDT, Hugo ***@***.***> wrote:  
 
 


Closed #192.
