### ISSUE TITLE
Remove "send feedback/issues to crash@stabyourself.net" from the window title

### ISSUE THREAD

**Issue by YouKnowHer** [Mari0-CE/Mari0-Community-Edition#73]
I think it should be pretty obvious why

**Comment by WillWare** [comment]
Having the constantly updating FPS in the title makes it hard for capture software to record the footage too, so yeah, this is definitely getting replaced.

**Comment by YouKnowHer** [comment]
Oh, that's unfortunate. Do you think the FPS could be shown somewhere else, then?

**Comment by WillWare** [comment]
Definitely! It'll be put inside the game somewhere with a toggle.

**Comment by HugoBDesigner** [comment]
Maybe create an utilitarian screen for useful data and include the FPS there? Unless it'd be more useful/practical on its own.
I'm thinking of something kinda like Mari0:HEC, which would be very useful for map-making:
![image](https://user-images.githubusercontent.com/6296061/44265782-7286c480-a1fe-11e8-9c3f-2829ff46664d.png)
