### ISSUE TITLE
[Bug] Big Mario cannot trigger fizzlers that are below his body.

### ISSUE THREAD

**Issue by Someone671** [Mari0-CE/Mari0-Community-Edition#91]
The title can pretty much explain the bug. Here's a .gif if you don't understand it:
![bigmariofizzlerglitch](https://user-images.githubusercontent.com/42733310/44648162-61159780-aa0a-11e8-9cda-65df1dc2c4a1.gif)

Note that when Big Mario goes through the fizzler, the fizzler does not clear out his portals.
BTW Fire Mario also have this issue.

**Comment by HugoBDesigner** [comment]
Currently, the game only fizzles your portals if half of your body crosses the fizzler. It'll require some amount of rewriting of fizzlers to get them working on partial touch again.

**Comment by Someone671** [comment]
Well that might explain why when you duck-jumped (not showed here) on the fizzler it finally fizzles your portal.
