### ISSUE TITLE
Transferring repository ownership to "Mari0 CE" organization

### ISSUE THREAD

**Issue by HugoBDesigner** [Mari0-CE/Mari0-Community-Edition#92]
I figured it'd be more organized and generally wiser to transfer the ownership of CE from my personal account to a GitHub organization I created, [Mari0 CE](https://github.com/Mari0-CE). I've taken inspiration from the [BEEmod](https://github.com/BEEmod) repository, which seems more "professional" and cleaner. I would, however, like to get some opinions and/or objections before I proceed.

**Comment by HugoBDesigner** [comment]
Pros:
 - The project is not tied to me personally, so everyone gets to change it with more freedom;
 - It's easier to organize, in case we create a new repository;
 - We can assemble teams for specific tasks or skillsets;
 - It's easier to find.

Cons:
 - Forks and stars will lose their linkage to the repository;
 - Existing links to the repository will cease working.

**Comment by ncrecc** [comment]
Regarding stars, watches, and existing links, that seems relatively low-risk since most people here came from stys and would be aware of an updated link if it were posted in the Community Edition topic. Not sure about forks, though.

**Comment by Noahkiq** [comment]
forks, stars, watches, and existing links will remain intact if you use github's ownership transfer tool.

**Comment by Technidecimal** [comment]
![image](https://user-images.githubusercontent.com/23534814/45266395-95388180-b428-11e8-8705-2edb804d4f9e.png)

Is it tomorrow right away yet? 🤔

**Comment by Noahkiq** [comment]
every single open issue has now been marked as "last updated 10 minutes ago". weird.
